apiVersion: mutations.gatekeeper.sh/v1
kind: Assign
metadata:
  name: pinniped-internal
spec:
  applyTo:
  - groups: ["config.concierge.pinniped.tmc.cloud.vmware.com"]
    kinds: ["CredentialIssuer"]
    versions: ["v1alpha1"]
  match:
    scope: Cluster
    name: cluster-auth-pinniped-config
    kinds:
    - apiGroups: ["*"]
      kinds: ["CredentialIssuer"]
  location: spec.impersonationProxy.service.annotations."service.beta.kubernetes.io/azure-load-balancer-internal"
  parameters:
    assign:
      value:  "true"