apiVersion: mutations.gatekeeper.sh/v1
kind: AssignMetadata
metadata:
  name: pinniped-internal
spec:
  match:
    scope: Namespaced
    namespaces: ['vmware-system-tmc']
    name: cluster-auth-pinniped-impersonation-proxy-load-balancer
    kinds:
    - apiGroups: [""]
      kinds: ["Service"]
  location: 'metadata.annotations."service.beta.kubernetes.io/azure-load-balancer-internal"'
  parameters:
    assign:
      value:  "true"